title:            SOULHEALINGRADIO
description:      "We play vinyl records"
logo_black:       logo_black.png
logo_white:       logo_white.png
logo:             shr_big.png
disqus_shortname: soulhealingradio
share:            true

url:              http://soulhealingradio.de

# Owner/author information
owner:
  name:           Soulhealing Radio
  avatar:         shr_big.png
  email:          soulhealingradio@elpg.de
  description:    "We play vinyl records"
  twitter:        soulhealing_fm
  facebook:       soulhealingradio
  mixcloud:       soulhealingradio

google_analytics:   UA-47472538-2

# Links to include in footer navigation
# For external links add external: true
links:
  - title: Live
    url: /live
  - title: About
    url: /about
  - title: Party
    url: /party
  - title: Shop
    url: http://soulhealing.spreadshirt.de
    external: true

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Europe/Berlin
future:      true
highlighter: rouge
markdown:    kramdown
paginate:    5
paginate_path: "page:num"

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:title

gems:
  - jekyll-paginate
